import 'package:learingdart/core/entities/invoice_data.dart';

class FullInvoiceData extends RawInvoice {
  final List<RawInvoice> details;

  FullInvoiceData({
    required this.details,
    required super.invMasSno,
    required super.invDetSno,
    super.invoiceDate,
    super.paymentType,
    super.invoiceNo,
    super.dueDate,
    super.invoiceExpiredDate,
    required super.chusMasNo,
    super.chusName,
    required super.comMasSno,
    super.companyName,
    super.invRemarks,
    required super.remarks,
    super.vatCategory,
    super.currencyCode,
    super.currencyName,
    required super.totalWithoutVt,
    required super.totalVt,
    required super.total,
    required super.itemQty,
    required super.itemUnitPrice,
    required super.itemTotalAmount,
    required super.vatPercentage,
    required super.vatAmount,
    required super.itemWithoutVat,
    super.itemDescription,
    super.auditBy,
    super.warranty,
    super.vatType,
    super.goodsStatus,
    super.deliveryStatus,
    super.auditDate,
    super.grandCount,
    super.dailyCount,
    super.approvalStatus,
    super.approvalDate,
    super.pDate,
    super.customerIdType,
    super.customerIdNo,
    required super.zReportSno,
    super.zReportStatus,
    super.zReportStatus1,
    super.zReportDate,
    super.zReportDate1,
    super.zReportDate2,
    required super.controlNo,
    super.reason,
    required super.status,
    super.mobile,
    super.email,
  });

  factory FullInvoiceData.fromJson(Map<String, dynamic> json) {
    return FullInvoiceData(
      // details: (json['details'] as List<RawInvoice>)
      //     .map((item) => RawInvoice.fromJson(item))
      //     .toList(),
      details: json['details'] ?? [],
      invMasSno: json['Inv_Mas_Sno'],
      invDetSno: json['Inv_Det_Sno'],
      invoiceDate: json['Invoice_Date'],
      paymentType: json['Payment_Type'],
      invoiceNo: json['Invoice_No'],
      dueDate: json['Due_Date'],
      invoiceExpiredDate: json['Invoice_Expired_Date'],
      chusMasNo: json['Chus_Mas_No'],
      chusName: json['Chus_Name'],
      comMasSno: json['Com_Mas_Sno'],
      companyName: json['Company_Name'],
      invRemarks: json['Inv_Remarks'],
      remarks: json['Remarks'],
      vatCategory: json['vat_category'],
      currencyCode: json['Currency_Code'],
      currencyName: json['Currency_Name'],
      totalWithoutVt: json['Total_Without_Vt'],
      totalVt: json['Total_Vt'],
      total: json['Total'],
      itemQty: json['Item_Qty'],
      itemUnitPrice: json['Item_Unit_Price'],
      itemTotalAmount: json['Item_Total_Amount'],
      vatPercentage: json['Vat_Percentage'],
      vatAmount: json['Vat_Amount'],
      itemWithoutVat: json['Item_Without_vat'],
      itemDescription: json['Item_Description'],
      auditBy: json['AuditBy'],
      warranty: json['warrenty'],
      vatType: json['Vat_Type'],
      goodsStatus: json['goods_status'],
      deliveryStatus: json['delivery_status'],
      auditDate: json['Audit_Date'],
      grandCount: json['grand_count'],
      dailyCount: json['daily_count'],
      approvalStatus: json['approval_status'],
      approvalDate: json['approval_date'],
      pDate: json['p_date'],
      customerIdType: json['Customer_ID_Type'],
      customerIdNo: json['Customer_ID_No'],
      zReportSno: json['Zreport_Sno'],
      zReportStatus: json['Zreport_Status'],
      zReportStatus1: json['Zreport_Status1'],
      zReportDate: json['Zreport_Date'],
      zReportDate1: json['Zreport_Date1'],
      zReportDate2: json['Zreport_Date2'],
      controlNo: json['Control_No'] ?? '',
      reason: json['Reason'],
      status: json['Status'],
      mobile: json['Mobile'],
      email: json['Email'],
    );
  }
}
